In [2]:
import pandas as pd
import statistics as st#used for mode median 
import numpy as np
#df data frame A DataFrame is table-like structure.

In [3]:
df = pd.read_csv("Iris.csv")

In [4]:
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [5]:
df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [7]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [11]:
df.describe(include="all")# all catogirical columns also

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
count,150.000000,150.000000,150.000000,150.000000,150.000000,150
unique,NaN,NaN,NaN,NaN,NaN,3
top,NaN,NaN,NaN,NaN,NaN,Iris-setosa
freq,NaN,NaN,NaN,NaN,NaN,50
mean,75.500000,5.843333,3.054000,3.758667,1.198667,NaN
std,43.445368,0.828066,0.433594,1.764420,0.763161,NaN
min,1.000000,4.300000,2.000000,1.000000,0.100000,NaN
25%,38.250000,5.100000,2.800000,1.600000,0.300000,NaN
50%,75.500000,5.800000,3.000000,4.350000,1.300000,NaN
75%,112.750000,6.400000,3.300000,5.100000,1.800000,NaN
max,150.000000,7.900000,4.400000,6.900000,2.500000,NaN

In [12]:
df.shape #(row,col)

(150, 6)

In [10]:
df.size#Total elements.

900

In [13]:
df.columns

Index(['Id', 'SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm',
       'Species'],
      dtype='object')

In [14]:
df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [15]:
df.ndim#Number of dimensions.

2

In [21]:
# Group by species and describe sepal length Groups rows based on species.
summary = df.groupby('Species')['SepalLengthCm'].describe()

print("\nSummary Statistics:")
print(summary)

Summary Statistics:
                 count   mean       std  min    25%  50%  75%  max
Species
Iris-setosa       50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8
Iris-versicolor   50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0
Iris-virginica    50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9

In [22]:
# Custom statistics function
def custom_describe(x):
    mode_value = st.mode(x)#Most repeated value.
    median_value = np.median(x) #Middle value after sorting.
    return pd.Series(#Returns multiple values as Series.
        [x.count(), x.mean(), x.std(),
         mode_value, median_value,
         x.min(), x.max()],
        index=['count', 'mean', 'std',
               'mode', 'median',
               'min', 'max']
    )

In [23]:
# Apply custom function
summary_with_mode_median = df.groupby('Species')['SepalLengthCm'].apply(custom_describe)
#Group data by species
#Send each group to custom function
#Function calculates statistics
#Results combined together
print("\nCustom Statistics:")
print(summary_with_mode_median)

Custom Statistics:
Species
Iris-setosa      count     50.000000
                 mean       5.006000
                 std        0.352490
                 mode       5.100000
                 median     5.000000
                 min        4.300000
                 max        5.800000
Iris-versicolor  count     50.000000
                 mean       5.936000
                 std        0.516171
                 mode       5.500000
                 median     5.900000
                 min        4.900000
                 max        7.000000
Iris-virginica   count     50.000000
                 mean       6.588000
                 std        0.635880
                 mode       6.300000
                 median     6.500000
                 min        4.900000
                 max        7.900000
Name: SepalLengthCm, dtype: float64

In [24]:
# Mode
mode_summary = df.groupby('Species')['SepalLengthCm'].apply(lambda x: st.mode(x))
#Small anonymous function.
print("\nMode:")
print(mode_summary)

Mode:
Species
Iris-setosa        5.1
Iris-versicolor    5.5
Iris-virginica     6.3
Name: SepalLengthCm, dtype: float64

In [25]:

# Median
median_summary = df.groupby('Species')['SepalLengthCm'].median()

print("\nMedian:")
print(median_summary)

Median:
Species
Iris-setosa        5.0
Iris-versicolor    5.9
Iris-virginica     6.5
Name: SepalLengthCm, dtype: float64

In [26]:

# Mean
mean_summary = df.groupby('Species')['SepalLengthCm'].mean()

print("\nMean:")
print(mean_summary)

Mean:
Species
Iris-setosa        5.006
Iris-versicolor    5.936
Iris-virginica     6.588
Name: SepalLengthCm, dtype: float64

In [27]:
# Numeric values for each species
species_numeric_value = df.groupby('Species').size().tolist()
#Convert Group Sizes to List
print("\nNumeric Values:")
print(species_numeric_value)

Numeric Values:
[50, 50, 50]

In [28]:
# Full statistics for all species
species_stats = df.groupby('Species').describe()
#Statistics for ALL numeric columns grouped by species.
print("\nSpecies Statistics:")
print(species_stats)

Species Statistics:
                   Id                                                        \
                count   mean       std    min     25%    50%     75%    max
Species
Iris-setosa      50.0   25.5  14.57738    1.0   13.25   25.5   37.75   50.0
Iris-versicolor  50.0   75.5  14.57738   51.0   63.25   75.5   87.75  100.0
Iris-virginica   50.0  125.5  14.57738  101.0  113.25  125.5  137.75  150.0

                SepalLengthCm         ... PetalLengthCm      PetalWidthCm  \
                        count   mean  ...           75%  max        count
Species                               ...
Iris-setosa              50.0  5.006  ...         1.575  1.9         50.0
Iris-versicolor          50.0  5.936  ...         4.600  5.1         50.0
Iris-virginica           50.0  6.588  ...         5.875  6.9         50.0


                  mean       std  min  25%  50%  75%  max
Species
Iris-setosa      0.244  0.107210  0.1  0.2  0.2  0.3  0.6
Iris-versicolor  1.326  0.197753  1.0  1.2  1.3  1.5  1.8
Iris-virginica   2.026  0.274650  1.4  1.8  2.0  2.3  2.5

[3 rows x 40 columns]

In [29]:
# Individual species statistics

setosa_stats = df[df['Species'] == 'Iris-setosa'].describe()

In [30]:
versicolor_stats = df[df['Species'] == 'Iris-versicolor'].describe()

virginica_stats = df[df['Species'] == 'Iris-virginica'].describe()

In [31]:
# Print statistics
print("\nSetosa Statistics:")
print(setosa_stats)

Setosa Statistics:
             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000

In [32]:
print("\nVersicolor Statistics:")
print(versicolor_stats)

Versicolor Statistics:
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000

In [33]:
print("\nVirginica Statistics:")
print(virginica_stats)

Virginica Statistics:
              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000       50.00000     50.000000      50.000000      50.00000
mean   125.50000        6.58800      2.974000       5.552000       2.02600
std     14.57738        0.63588      0.322497       0.551895       0.27465
min    101.00000        4.90000      2.200000       4.500000       1.40000
25%    113.25000        6.22500      2.800000       5.100000       1.80000
50%    125.50000        6.50000      3.000000       5.550000       2.00000
75%    137.75000        6.90000      3.175000       5.875000       2.30000
max    150.00000        7.90000      3.800000       6.900000       2.50000